# Generated by Django 6.0.1 on 2026-02-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_newspaper_article_is_ai_selection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='target_country',
            field=models.CharField(choices=[('KM', 'Comores'), ('FR', 'France'), ('AF', 'Afrique'), ('INT', 'International')], default='INT', max_length=10),
        ),
    ]
