# Generated by Django 6.0.1 on 2026-02-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_newspaper_target_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Ex: fa-stethoscope', max_length=50),
        ),
    ]
