# Generated by Django 6.0.3 on 2026-03-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='wants_daily',
            field=models.BooleanField(default=True),
        ),
    ]
