# Generated by Django 6.0.3 on 2026-03-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_subscriber_is_verified_subscriber_unsubscribe_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='target_country',
            field=models.CharField(choices=[('KM', 'Comores'), ('FR', 'France'), ('AF', 'Afrique'), ('MO', 'Moyen-Orient'), ('EUR', 'Europe'), ('AS', 'Asie'), ('AM', 'Amériques'), ('INT', 'International')], default='INT', max_length=10),
        ),
    ]
