# Generated by Django 6.0.1 on 2026-03-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_newspaper_target_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio_duration',
            field=models.CharField(blank=True, help_text='Ex: 14 min écoute', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_audio_news',
            field=models.BooleanField(default=False),
        ),
    ]
