# Generated by Django 6.0.1 on 2026-03-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_article_audio_duration_article_is_audio_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Lien vers le fichier MP3 ou le flux audio', max_length=500, null=True),
        ),
    ]
